# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"assign_doc": "script.ipynb",
         "clean_md_lines": "docs.ipynb",
         "show_doc": "docs.ipynb",
         "store_attr": "script.ipynb",
         "str2bool": "script.ipynb",
         "store_true": "script.ipynb",
         "store_false": "script.ipynb",
         "bool_arg": "script.ipynb",
         "args_from_prog": "script.ipynb",
         "call_parse": "script.ipynb",
         "maybe_attr": "script.ipynb",
         "basic_repr": "script.ipynb",
         "CustomFormatter": "script.ipynb",
         "is_array": "script.ipynb",
         "is_iter": "script.ipynb",
         "listify": "script.ipynb",
         "clean_type": "script.ipynb",
         "Param": "script.ipynb",
         "anno_parser": "script.ipynb",
         "PathLike": "utils.ipynb",
         "ListOfPaths": "utils.ipynb",
         "ListOfStrings": "utils.ipynb",
         "ls": "utils.ipynb",
         "listdirs": "utils.ipynb",
         "Path.ls": "utils.ipynb",
         "Path.listdirs": "utils.ipynb",
         "get_files": "utils.ipynb",
         "get_image_files": "utils.ipynb",
         "get_video_files": "utils.ipynb",
         "image_extensions": "utils.ipynb",
         "video_extensions": "utils.ipynb",
         "flatten": "utils.ipynb",
         "mkdir": "utils.ipynb",
         "uniqueify": "utils.ipynb",
         "clean_filename": "utils.ipynb"}

modules = ["docs.py",
           "script.py",
           "utils.py"]

doc_url = "https://rsomani95.github.io/os_utilities/"

git_url = "https://github.com/rsomani95/os_utilities/tree/master/"

def custom_doc_links(name): return None
