# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PathLike": "utils.ipynb",
         "ListOfPaths": "utils.ipynb",
         "ListOfStrings": "utils.ipynb",
         "ls": "utils.ipynb",
         "listdirs": "utils.ipynb",
         "Path.ls": "utils.ipynb",
         "Path.listdirs": "utils.ipynb",
         "get_files": "utils.ipynb",
         "get_image_files": "utils.ipynb",
         "get_video_files": "utils.ipynb",
         "image_extensions": "utils.ipynb",
         "video_extensions": "utils.ipynb",
         "flatten": "utils.ipynb",
         "mkdir": "utils.ipynb",
         "uniqueify": "utils.ipynb",
         "clean_filename": "utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://rsomani95.github.io/os_utilities/"

git_url = "https://github.com/rsomani95/os_utilities/tree/master/"

def custom_doc_links(name): return None
